// RMM fonts created through fontello
// Files used to create the fonts are here: `assets/images/font-svgs`

export const RMM_ARR = [
  'add',
  'alert',
  'avatar',
  'back',
  'backup',
  'cog',
  'daily',
  'demodevices',
  'dragdrop',
  'forumdisplay',
  'imageplaceholder',
  'info',
  'layers',
  'menu',
  'moreoptions',
  'repeat',
  'star',
  'trashcan',
  'videowall',
  // Dups with marcom but still in RMM fonts
  // 'calendar',
  // 'clock',
  // 'more',
  // 'profile',
] as const

export type RMM_ARR_T = typeof RMM_ARR[number]

export const MARCOM_ARR = [
  'apple',
  'calendar-check',
  'calendar',
  'check',
  'checkcircle',
  'checksolid',
  'chevrondown',
  'chevrondowncircle',
  'chevronleft',
  'chevronleftcircle',
  'chevronright',
  'chevronrightcircle',
  'chevronup',
  'chevronupcircle',
  'circle',
  'clock',
  'close',
  'downloadcircle',
  'downloadsolid',
  'editpencil',
  'exclamation',
  'exclamationcircle',
  'exclamationsolid',
  'external',
  'facebook',
  'favorite',
  'grid',
  'infocircle',
  'instagram',
  'link',
  'linkedin',
  'listcircle',
  'locales',
  'mail',
  'minus',
  'minuscircle',
  'minussolid',
  'more',
  'paddledown',
  'paddleleft',
  'paddleright',
  'paddleup',
  'pausecircle',
  'pinterest',
  'playalt',
  'playcircle',
  'playsolid',
  'plus',
  'pluscircle',
  'plussolid',
  'profile',
  'qqweibo',
  'questioncircle',
  'questionsolid',
  'qzone',
  'renren',
  'replay',
  'replaycircle',
  'reset',
  'resetcircle',
  'resetsolid',
  'screen',
  'searchicon',
  'share',
  'snapchat',
  'sortable',
  'stopcircle',
  'stopsolid',
  'tags',
  'tumblr',
  'twitter',
  'uploadsolid',
  'weibo',
] as const

export type MARCOM_ARR_T = typeof RMM_ARR[number]

export const IMAGES = Object.freeze({
  add: require('./images/font-svgs/add.svg'),
  alert: require('./images/font-svgs/alert.svg'),
  avatar: require('./images/font-svgs/avatar.svg'),
  back: require('./images/font-svgs/back.svg'),
  backup: require('./images/font-svgs/backup.svg'),
  calendar: require('./images/font-svgs/calendar.svg'),
  clock: require('./images/font-svgs/clock.svg'),
  cog: require('./images/font-svgs/cog.svg'),
  daily: require('./images/font-svgs/repeat.svg'),
  delete: require('./images/font-svgs/trashcan.svg'),
  demodevices: require('./images/font-svgs/demodevices.svg'),
  dragndrop: require('./images/font-svgs/dragdrop.svg'),
  forumdisplay: require('./images/font-svgs/forumdisplay.svg'),
  imageplaceholder: require('./images/font-svgs/imageplaceholder.svg'),
  info: require('./images/font-svgs/info.svg'),
  layers: require('./images/font-svgs/layers.svg'),
  multiAsset: require('./images/font-svgs/multi-asset.svg'),
  portrait: require('./images/font-svgs/portrait.svg'),
  menu: require('./images/font-svgs/menu.svg'),
  more: require('./images/font-svgs/more.svg'),
  moreoptions: require('./images/font-svgs/moreoptions.svg'),
  profile: require('./images/font-svgs/profile.svg'),
  singleAsset: require('./images/font-svgs/single-asset.svg'),
  star: require('./images/font-svgs/star.svg'),
  trashcan: require('./images/font-svgs/trashcan.svg'),
  videowall: require('./images/font-svgs/videowall.svg'),
})
